import "./globals.css";

import Header from "./components/Header";
import Footer from "./components/Footer";



export const metadata = {
  title: "Best Stock Broker in India - Discount Stock Broker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-950 text-white">

        <Header />

        <main>{children}</main>

        <Footer />

      </body>
    </html>
  );
}
